# Generated by Django 4.2.23 on 2025-08-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_notes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
